# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/some-files/codes/auto-mm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/some-files/codes/auto-mm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/some-files/codes/auto-mm/CMakeFiles /mnt/e/some-files/codes/auto-mm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/some-files/codes/auto-mm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named auto-mm

# Build rule for target.
auto-mm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auto-mm
.PHONY : auto-mm

# fast build rule for target.
auto-mm/fast:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/build
.PHONY : auto-mm/fast

src/atom.o: src/atom.cpp.o

.PHONY : src/atom.o

# target to build an object file
src/atom.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/atom.cpp.o
.PHONY : src/atom.cpp.o

src/atom.i: src/atom.cpp.i

.PHONY : src/atom.i

# target to preprocess a source file
src/atom.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/atom.cpp.i
.PHONY : src/atom.cpp.i

src/atom.s: src/atom.cpp.s

.PHONY : src/atom.s

# target to generate assembly for a file
src/atom.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/atom.cpp.s
.PHONY : src/atom.cpp.s

src/calcval.o: src/calcval.cpp.o

.PHONY : src/calcval.o

# target to build an object file
src/calcval.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/calcval.cpp.o
.PHONY : src/calcval.cpp.o

src/calcval.i: src/calcval.cpp.i

.PHONY : src/calcval.i

# target to preprocess a source file
src/calcval.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/calcval.cpp.i
.PHONY : src/calcval.cpp.i

src/calcval.s: src/calcval.cpp.s

.PHONY : src/calcval.s

# target to generate assembly for a file
src/calcval.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/calcval.cpp.s
.PHONY : src/calcval.cpp.s

src/funsys.o: src/funsys.cpp.o

.PHONY : src/funsys.o

# target to build an object file
src/funsys.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/funsys.cpp.o
.PHONY : src/funsys.cpp.o

src/funsys.i: src/funsys.cpp.i

.PHONY : src/funsys.i

# target to preprocess a source file
src/funsys.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/funsys.cpp.i
.PHONY : src/funsys.cpp.i

src/funsys.s: src/funsys.cpp.s

.PHONY : src/funsys.s

# target to generate assembly for a file
src/funsys.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/funsys.cpp.s
.PHONY : src/funsys.cpp.s

src/lammps.o: src/lammps.cpp.o

.PHONY : src/lammps.o

# target to build an object file
src/lammps.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/lammps.cpp.o
.PHONY : src/lammps.cpp.o

src/lammps.i: src/lammps.cpp.i

.PHONY : src/lammps.i

# target to preprocess a source file
src/lammps.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/lammps.cpp.i
.PHONY : src/lammps.cpp.i

src/lammps.s: src/lammps.cpp.s

.PHONY : src/lammps.s

# target to generate assembly for a file
src/lammps.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/lammps.cpp.s
.PHONY : src/lammps.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/molecule.o: src/molecule.cpp.o

.PHONY : src/molecule.o

# target to build an object file
src/molecule.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/molecule.cpp.o
.PHONY : src/molecule.cpp.o

src/molecule.i: src/molecule.cpp.i

.PHONY : src/molecule.i

# target to preprocess a source file
src/molecule.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/molecule.cpp.i
.PHONY : src/molecule.cpp.i

src/molecule.s: src/molecule.cpp.s

.PHONY : src/molecule.s

# target to generate assembly for a file
src/molecule.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/molecule.cpp.s
.PHONY : src/molecule.cpp.s

src/nanotube.o: src/nanotube.cpp.o

.PHONY : src/nanotube.o

# target to build an object file
src/nanotube.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/nanotube.cpp.o
.PHONY : src/nanotube.cpp.o

src/nanotube.i: src/nanotube.cpp.i

.PHONY : src/nanotube.i

# target to preprocess a source file
src/nanotube.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/nanotube.cpp.i
.PHONY : src/nanotube.cpp.i

src/nanotube.s: src/nanotube.cpp.s

.PHONY : src/nanotube.s

# target to generate assembly for a file
src/nanotube.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/nanotube.cpp.s
.PHONY : src/nanotube.cpp.s

src/random.o: src/random.cpp.o

.PHONY : src/random.o

# target to build an object file
src/random.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/random.cpp.o
.PHONY : src/random.cpp.o

src/random.i: src/random.cpp.i

.PHONY : src/random.i

# target to preprocess a source file
src/random.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/random.cpp.i
.PHONY : src/random.cpp.i

src/random.s: src/random.cpp.s

.PHONY : src/random.s

# target to generate assembly for a file
src/random.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/random.cpp.s
.PHONY : src/random.cpp.s

src/stropt.o: src/stropt.cpp.o

.PHONY : src/stropt.o

# target to build an object file
src/stropt.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/stropt.cpp.o
.PHONY : src/stropt.cpp.o

src/stropt.i: src/stropt.cpp.i

.PHONY : src/stropt.i

# target to preprocess a source file
src/stropt.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/stropt.cpp.i
.PHONY : src/stropt.cpp.i

src/stropt.s: src/stropt.cpp.s

.PHONY : src/stropt.s

# target to generate assembly for a file
src/stropt.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/stropt.cpp.s
.PHONY : src/stropt.cpp.s

src/varsys.o: src/varsys.cpp.o

.PHONY : src/varsys.o

# target to build an object file
src/varsys.cpp.o:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/varsys.cpp.o
.PHONY : src/varsys.cpp.o

src/varsys.i: src/varsys.cpp.i

.PHONY : src/varsys.i

# target to preprocess a source file
src/varsys.cpp.i:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/varsys.cpp.i
.PHONY : src/varsys.cpp.i

src/varsys.s: src/varsys.cpp.s

.PHONY : src/varsys.s

# target to generate assembly for a file
src/varsys.cpp.s:
	$(MAKE) -f CMakeFiles/auto-mm.dir/build.make CMakeFiles/auto-mm.dir/src/varsys.cpp.s
.PHONY : src/varsys.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... auto-mm"
	@echo "... edit_cache"
	@echo "... src/atom.o"
	@echo "... src/atom.i"
	@echo "... src/atom.s"
	@echo "... src/calcval.o"
	@echo "... src/calcval.i"
	@echo "... src/calcval.s"
	@echo "... src/funsys.o"
	@echo "... src/funsys.i"
	@echo "... src/funsys.s"
	@echo "... src/lammps.o"
	@echo "... src/lammps.i"
	@echo "... src/lammps.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/molecule.o"
	@echo "... src/molecule.i"
	@echo "... src/molecule.s"
	@echo "... src/nanotube.o"
	@echo "... src/nanotube.i"
	@echo "... src/nanotube.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/stropt.o"
	@echo "... src/stropt.i"
	@echo "... src/stropt.s"
	@echo "... src/varsys.o"
	@echo "... src/varsys.i"
	@echo "... src/varsys.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

